name: Lint Charts

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: debian:stable-slim
    steps:
    - uses: actions/checkout@v1
    - name: Helm Lint
      run: |
        apt-get update && apt-get -qq install curl bash
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        helm lint stable/activemq-artemis
